name: Update streak stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Streak Stats Action
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          token: ${{ secrets.STREAK_STATS_TOKEN }}
          options: "user=SalehAbdulla&theme=dark&hide_border=false"
          path: "profile-readme-streak-stats.svg"

      - name: Commit and push SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update streak stats SVG"
          file_pattern: "profile-readme-streak-stats.svg"
